version: "3.9"
services:
  backend:
    image: python:3.11-slim-buster
    working_dir: /app
    volumes:
      - ../backend/app:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --reload --host 0.0.0.0
  frontend:
    image: node:18-slim
    working_dir: /app
    volumes:
      - ../frontend:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    command: pnpm run dev
    depends_on:
      - backend
